# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [1]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

#Example of using permutations() method
t = list(itertools.permutations('123', 3))

def generate_permutations(dim):
    """
    The function generates all possible permutations of indices for a matrix of size dim x dim.
    """
    list_permutation = list(itertools.permutations(range(dim), dim))
    return list_permutation

def products_permutation(matrix, dim):
    """
    The function finds the products of all permutations and adds them to the list
    """
    list_permutation = generate_permutations(dim)
    products = []
    
    for permutation in list_permutation:
        product = 1
        pi = 0
        for i in range(len(permutation)):
            product *= matrix[i][permutation[i]]
            for j in range(i+1, len(permutation)):
                if permutation[i] > permutation[j]:
                    pi += 1
        if pi % 2 == 1:
            products.append(-product)
        else:
            products.append(product)

    return products

def all_sum():
    """
    The function adds all the products and finds the determinant
    """
    product_last_list = products_permutation(matrix, dim)
    sum = 0
    for product in product_last_list:
        sum += product
    return sum
    
while True:
    try:
        dim = int(input("Введіть розмірність квадратної матриці (натуральне число): "))
        if dim <= 0:
            print("Розмірність має бути додатнім числом. Спробуйте ще раз.")
            continue
        break
    except ValueError:
        print("Будь ласка, введіть натуральне число.")

matrix = random_matrix(dim)
print("Згенерована матриця:")
print(matrix)

det = all_sum()
print("Визначник матриці:", det)

np_det = np.linalg.det(matrix)
print("Визначник матриці за допомогою np.linalg.det:", np_det)

Згенерована матриця:
[[1 2 2 3 8 0 2 9 9 1]
 [6 8 6 1 5 7 7 9 8 4]
 [6 5 6 1 2 7 7 6 1 7]
 [1 3 7 6 7 4 1 9 8 3]
 [1 3 5 5 4 2 5 9 0 9]
 [9 7 9 6 3 6 5 7 2 7]
 [6 6 8 9 7 8 2 0 2 2]
 [3 2 9 3 3 2 9 6 3 7]
 [4 1 8 0 0 7 1 9 5 2]
 [4 2 0 3 0 0 8 2 0 9]]
Визначник матриці: 51429732
Визначник матриці за допомогою np.linalg.det: 51429732.00000001
